# Generated by Django 6.0 on 2025-12-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(db_index=True, editable=False, verbose_name='2FA secret key.')),
            ],
            options={
                'verbose_name': 'Two Factor Secret Key',
                'verbose_name_plural': 'Two Factor Secret Key',
            },
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='country name')),
                ('code', models.CharField(max_length=10, verbose_name='country code')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'code'], name='country_name_code')],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_country_name_code')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=7, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='YYYY-MM-DD formate.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/%Y/%m/%d')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_admin', models.BooleanField(db_default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(db_default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.countrycode')),
                ('two_factor_secret_key', models.OneToOneField(blank=True, help_text='two_factor_secret_key not null\n        means 2FA is active for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.twofa', verbose_name='2FA secret key')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['id'], name='users_user_id_1cecd0_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx')],
            },
        ),
    ]
