# Generated by Django 6.0 on 2025-12-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=123, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
