# Generated by Django 6.0 on 2025-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
