# Generated by Django 6.0 on 2026-01-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_product_rating_count_product_rating_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(db_default=0.0, db_index=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
