# Generated by Django 6.0 on 2026-02-11 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_discount_name_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
